#!/bin/bash

# 1. Stage all changes
git add .

# 2. Commit with a message
git commit -m "Auto Commit Generated by Script"

# 3. Get the current branch name dynamically
BRANCH=$(git branch --show-current)

# 4. Push to the remote repository
git push origin "$BRANCH"

echo "Changes have been staged, committed, and pushed to the $BRANCH branch successfully."